#!/usr/bin/env bash

# $1 - Git repository name
# $2 - Branch name
startup() {
    echo "Watch started: $*"
}

# $1 - Git repository name
# $2 - Branch name
no_changes() {
    echo "Nothing changed: $*"
}

# $1 - Git repository name
# $2 - Branch name
# $3 - Commit details
change_pulled() {
    echo "Changes pulled: $*"
    echo "Starting build for commit: $@"
    mkdir ~/git-watcher-builder/builds/ViaVersion
    mkdir ~/git-watcher-builder/builds/ViaVersion_t
    wget -O ~/git-watcher-builder/builds/ViaVersion_t/ViaVersion_DEV.zip https://nightly.link/ViaVersion/ViaVersion/workflows/gradle/master/artifact.zip
    unzip ~/git-watcher-builder/builds/ViaVersion_t/ViaVersion_DEV.zip ~/git-watcher-builder/builds/ViaVersion_t/
    rm ~/git-watcher-builder/builds/ViaVersion_t/ViaVersion_DEV.zip
    mv ViaVersion-Bungee-*.jar ~/git-watcher-builder/builds/ViaVersion/ViaVersion-Bungee-*.jar
    rm -rf ~/git-watcher-builder/builds/ViaVersion_t
    
}

# $1 - Git repository name
# $2 - Branch name
# $3 - Commit details
pull_failed() {
    echo "Pull failed --> Exiting: $*"
    exit 1
}

# $1 - Git repository name
# $2 - New branch name
# $3 - Old branch name
branch_changed() {
    echo "Branch changed: $*"
}

# $1 - Git repository name
# $2 - Branch name
upstream_not_set() {
    echo "Upstream not set: $*"
}

# $1 - Git repository name
# $2 - Branch name
local_change() {
    echo "local file changed: $*"
}

# $1 - Git repository name
# $2 - Branch name
diverged() {
    echo "Diverged --> Exiting: $*"
    exit 1
}
